name: immigration_quebec
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  url_launcher: ^5.2.5
  flutter_linkify: ^2.1.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  http: ">=0.12.0+2 <0.14.0"
  flutter_custom_clippers: ^1.1.0
  html_unescape: ^1.0.1+3
  auto_size_text: ^2.1.0
  fluttertoast: ^3.1.3
  built_value: any
  built_collection: any
  flare_flutter: ^1.7.1
  dio: ">=3.0.4 <6.0.0"
  direct_select: ^1.0.0
  rxdart: ">=0.22.6 <0.26.0"
  bloc: ">=2.0.0 <9.0.0"
  gradient_widgets: ^0.5.0
  math_expressions: ^1.1.1
  simple_animations: ^1.3.4
  image_picker: ^0.6.1+11
  firebase_analytics: ^5.0.6
  firebase_database: ^3.1.0
  cloud_firestore: ^0.12.10
  firebase_auth: ^0.14.0+9
#  google_sign_in: ^4.0.14
  shared_preferences: ^0.5.4+5
  firebase_storage: ^3.0.8
  cached_network_image: ">=1.1.3 <3.0.0"
  intl: ^0.16.0
  firebase_messaging: ^5.1.8
  flutter_local_notifications: ^0.8.4
  photo_view: ^0.8.0
  firebase_core: ^0.4.1+5
  toast: ^0.1.5
  image: ^2.1.4
  connectivity: ^0.4.5+3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
fonts:
  - family: Raleway
    fonts:
      - asset: fonts/Raleway-Regular.ttf
      - asset: fonts/Raleway-Medium.ttf
        weight: 500
      - asset: assets/fonts/Raleway-SemiBold.ttf
        weight: 600
  - family: Schyler
    fonts:
      - asset: fonts/Schyler-Regular.ttf
      - asset: fonts/Schyler-Italic.ttf
        style: italic
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
        style: italic
      - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        weight: 300
  - family: Quando
    fonts:
      - asset: fonts/Quando.ttf
  - family: Satisfy
    fonts:
      - asset: fonts/Satisfy.ttf
  - family: Alike
    fonts:
      - asset: fonts/Alike-Regular.ttf
